### ISSUE TITLE
https connection failed using CY_SECURE_SOCKETS_PKCS_SUPPORT flag

### ISSUE THREAD

**Issue by shu-liu1314** [Infineon/mtb-example-optiga-mqtt-client#4]
Hi,

We updated our own project with the latest version of optiga-mqtt-client project. The previous version of optiga-mqtt-client project works well for us. After updating it to the latest release-v2.1.0, our project's https connection fails.

We found that it is because of the new DEFINE (CY_SECURE_SOCKETS_PKCS_SUPPORT) in the makefile.

Before: https ROOT CA is in CY_AWS_CERT_KEY_LOCATION_RAM
Now:    https ROOT CA is in CY_AWS_CERT_KEY_LOCATION_SECURE_STORAGE

I tried to manually change the location. It did not work. How should I fix this problem?

Thanks,
SL

**Comment by ShaikKarishma0** [comment]
Hi @shu-liu1314,

1. Can you please tell us which version of MTB are you using, is it 2.4 or 3.0 or 3.1?
2. What is the previous version of project that you were using?
3. Can you share the error message displayed on the terminal?

**Comment by shu-liu1314** [comment]
1. MTB 3.1
2. MTB 3.0,  mtb-example-optiga-mqtt-client/release-v1.1.0,  http-client/release-v1.1.1, 
3. Failed to connect to http server. Error=0x083a0007. Retrying...

**Comment by ShaikKarishma0** [comment]
HTTS connection fails mainly due to certificate mismatch / invalid certificates. Can you please check if all the certificates and credentials are correct and at the right location? 
As for the Root-CA, it does not matter where it comes from (RAM, some secure storage, etc.), as long as it is readable.

Also, please try using MTB 3.0 with mtb-example-optiga-mqtt-client/release-v2.0.0

**Comment by shu-liu1314** [comment]
It was because of the mbedtls user config.
